sudo: required
services:
  - docker

before_install:
  - docker build -t amurashou/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run amurashou/react-test npm run test -- --coverage

after_success:
  - docker build -t amurashou/multi-client ./client
  - docker build -t amurashou/multi-nginx ./nginx
  - docker build -t amurashou/multi-server ./server
  - docker build -t amurashou/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push amurashou/multi-client
  - docker push amurashou/multi-nginx
  - docker push amurashou/multi-server
  - docker push amurashou/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-110104577918"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
